-- Esquema inicial: locations, categories, items (app de cocina).
-- Aplicado sobre Neon. Sin RLS: el acceso ya no es cliente -> BD directo,
-- sino cliente -> Route Handlers (servidor) -> Neon.

create table public.locations (
  id   text primary key,
  name text not null,
  "desc" text default '',
  w    numeric,
  d    numeric,
  h    numeric
);

create table public.categories (
  id   integer generated always as identity primary key,
  name text unique not null
);

create table public.items (
  id     bigint generated by default as identity primary key,
  name   text not null,
  cat    text not null,
  loc_id text references public.locations(id) on delete set null,
  freq   text default '',
  notes  text default ''
);

create index items_loc_id_idx on public.items (loc_id);
create index items_cat_idx    on public.items (cat);
