// Datos semilla (BASE) para la función "Restaurar datos".
// Réplica de los datos cargados inicialmente en Supabase.

import type { Item, Location } from "./types";

export const SEED_LOCATIONS: Location[] = [
  { id: "arm", name: "Armario despensa", desc: "Columna 60cm — alimentos", w: 0.6, d: 0.6, h: 2.5 },
  { id: "nev", name: "Nevera", desc: "Módulo 70cm", w: 0.7, d: 0.6, h: 2 },
  { id: "nev-alto", name: "Mueble alto nevera", desc: "Mueble alto 70cm", w: 0.7, d: 0.35, h: 0.6 },
  { id: "m1-arr", name: "M1 — Cajón arriba", desc: "Utensilios de cocina", w: 0.9, d: 0.6, h: 0.3 },
  { id: "m1-med", name: "M1 — Cajón medio", desc: "Trapos, manoplas, textil", w: 0.9, d: 0.6, h: 0.35 },
  { id: "m1-aba", name: "M1 — Cajón abajo", desc: "Tuppers y fiambreras", w: 0.9, d: 0.6, h: 0.4 },
  { id: "freg", name: "Bajo fregadero", desc: "Puerta abatible — residuos", w: 0.7, d: 0.6, h: 0.9 },
  { id: "lvj", name: "Encimera lavavajillas", desc: "Superficie libre de apoyo", w: 0.6, d: 0.6, h: 0.05 },
  { id: "hor-hue", name: "Horno — Hueco superior", desc: "Pendiente", w: 0.6, d: 0.6, h: 0.7 },
  { id: "hor-aba1", name: "Horno — Cajón abajo 1", desc: "Pendiente", w: 0.6, d: 0.6, h: 0.3 },
  { id: "hor-aba2", name: "Horno — Cajón abajo 2", desc: "Bandejas, rejillas, papel horno", w: 0.6, d: 0.6, h: 0.3 },
  { id: "esc", name: "Escobero", desc: "70cm — limpieza y reciclaje", w: 0.7, d: 0.6, h: 2.5 },
  { id: "isla-izq-arr", name: "Isla izq — Cajón arriba", desc: "Especias y condimentos", w: 0.9, d: 0.6, h: 0.3 },
  { id: "isla-izq-med", name: "Isla izq — Cajón medio", desc: "Sartenes y tapas", w: 0.9, d: 0.6, h: 0.3 },
  { id: "isla-izq-aba", name: "Isla izq — Cajón abajo", desc: "Ollas y cazuelas", w: 0.9, d: 0.6, h: 0.4 },
  { id: "isla-der-arr", name: "Isla der — Cajón arriba", desc: "Cubiertos", w: 0.9, d: 0.6, h: 0.3 },
  { id: "isla-der-med", name: "Isla der — Cajón medio", desc: "Platos, tazas y bols", w: 0.9, d: 0.6, h: 0.3 },
  { id: "isla-der-aba", name: "Isla der — Cajón abajo", desc: "Vasos y copas", w: 0.9, d: 0.6, h: 0.4 },
  { id: "esq-arr", name: "Esquinero — Cajones arriba", desc: "Pendiente", w: 1, d: 0.4, h: 0.4 },
  { id: "esq-mes", name: "Esquinero — Mesada", desc: "Electrodomésticos pequeños", w: 1, d: 0.4, h: 0.05 },
  { id: "esq-aba", name: "Esquinero — Cajones abajo", desc: "Pendiente", w: 1, d: 0.4, h: 0.4 },
  { id: "estante", name: "Estante corrido 150cm", desc: "A 150cm altura — zona fregadero", w: 2.2, d: 0.35, h: 0.05 },
];

export const SEED_CATEGORIES: string[] = [
  "Electrodomésticos grandes",
  "Electrodomésticos pequeños",
  "Vajilla y mesa",
  "Utensilios de cocina",
  "Sartenes, ollas y cazuelas",
  "Horno y horneado",
  "Textil de cocina",
  "Almacenaje y fiambreras",
  "Residuos y limpieza",
  "Despensa — alimentos",
  "Varios",
];

export const SEED_ITEMS: Item[] = [
  { id: 1, name: "Nevera", cat: "Electrodomésticos grandes", locId: "nev", freq: "", notes: "" },
  { id: 2, name: "Lavavajillas", cat: "Electrodomésticos grandes", locId: "lvj", freq: "", notes: "" },
  { id: 3, name: "Horno", cat: "Electrodomésticos grandes", locId: "hor-hue", freq: "", notes: "" },
  { id: 4, name: "Placa de inducción (con extracción)", cat: "Electrodomésticos grandes", locId: "isla-izq-arr", freq: "", notes: "Centrada en 2,1m isla" },
  { id: 5, name: "Microondas", cat: "Electrodomésticos pequeños", locId: "esq-mes", freq: "", notes: "" },
  { id: 6, name: "Cafetera", cat: "Electrodomésticos pequeños", locId: "esq-mes", freq: "", notes: "" },
  { id: 7, name: "Tostadora", cat: "Electrodomésticos pequeños", locId: "esq-mes", freq: "", notes: "" },
  { id: 8, name: "Calentador de agua", cat: "Electrodomésticos pequeños", locId: "esq-mes", freq: "", notes: "" },
  { id: 9, name: "Robot de cocina / batidora de vaso", cat: "Electrodomésticos pequeños", locId: "m1-med", freq: "", notes: "Uso ocasional" },
  { id: 11, name: "Platos", cat: "Vajilla y mesa", locId: "isla-der-med", freq: "", notes: "" },
  { id: 12, name: "Vasos", cat: "Vajilla y mesa", locId: "isla-der-aba", freq: "", notes: "" },
  { id: 13, name: "Bols", cat: "Vajilla y mesa", locId: "isla-der-med", freq: "", notes: "" },
  { id: 14, name: "Tazas", cat: "Vajilla y mesa", locId: "isla-der-med", freq: "", notes: "" },
  { id: 15, name: "Cubiertos (cuchillos, tenedores...)", cat: "Vajilla y mesa", locId: "isla-der-arr", freq: "", notes: "" },
  { id: 16, name: "Vajilla especial / de fiesta", cat: "Vajilla y mesa", locId: "nev-alto", freq: "", notes: "" },
  { id: 17, name: "Fuentes grandes", cat: "Vajilla y mesa", locId: "nev-alto", freq: "", notes: "" },
  { id: 18, name: "Copas", cat: "Vajilla y mesa", locId: "isla-der-aba", freq: "", notes: "" },
  { id: 19, name: "Servilletas y mantelería", cat: "Vajilla y mesa", locId: null, freq: "", notes: "" },
  { id: 20, name: "Espátulas", cat: "Utensilios de cocina", locId: "isla-der-arr", freq: "diario", notes: "" },
  { id: 21, name: "Pelador", cat: "Utensilios de cocina", locId: "m1-arr", freq: "", notes: "" },
  { id: 22, name: "Tijeras de cocina", cat: "Utensilios de cocina", locId: "m1-arr", freq: "", notes: "" },
  { id: 23, name: "Pinzas", cat: "Utensilios de cocina", locId: "m1-arr", freq: "", notes: "" },
  { id: 24, name: "Cucharones y espumaderas", cat: "Utensilios de cocina", locId: "isla-der-arr", freq: "diario", notes: "" },
  { id: 25, name: "Abrebotellas / sacacorchos", cat: "Utensilios de cocina", locId: null, freq: "", notes: "" },
  { id: 26, name: "Rallador", cat: "Utensilios de cocina", locId: "m1-arr", freq: "", notes: "" },
  { id: 27, name: "Colador / escurridor", cat: "Utensilios de cocina", locId: null, freq: "", notes: "" },
  { id: 28, name: "Batidor de mano", cat: "Utensilios de cocina", locId: "m1-med", freq: "", notes: "" },
  { id: 29, name: "Cuchillos (bloque o soporte)", cat: "Utensilios de cocina", locId: null, freq: "", notes: "" },
  { id: 30, name: "Sartenes", cat: "Sartenes, ollas y cazuelas", locId: "isla-izq-med", freq: "", notes: "" },
  { id: 31, name: "Cazuelas", cat: "Sartenes, ollas y cazuelas", locId: "isla-izq-aba", freq: "", notes: "" },
  { id: 32, name: "Ollas", cat: "Sartenes, ollas y cazuelas", locId: "isla-izq-aba", freq: "", notes: "" },
  { id: 33, name: "Especias y condimentos", cat: "Sartenes, ollas y cazuelas", locId: "isla-izq-arr", freq: "", notes: "" },
  { id: 34, name: "Tapas de ollas y sartenes", cat: "Sartenes, ollas y cazuelas", locId: "isla-izq-med", freq: "", notes: "" },
  { id: 35, name: "Bandejas del horno", cat: "Horno y horneado", locId: "hor-aba2", freq: "", notes: "" },
  { id: 36, name: "Rejillas del horno", cat: "Horno y horneado", locId: "hor-aba2", freq: "", notes: "" },
  { id: 37, name: "Papel de horno", cat: "Horno y horneado", locId: "hor-aba2", freq: "", notes: "" },
  { id: 38, name: "Tablas de cortar", cat: "Horno y horneado", locId: "hor-aba2", freq: "", notes: "" },
  { id: 39, name: "Moldes (cake, muffins, pizza...)", cat: "Horno y horneado", locId: null, freq: "", notes: "" },
  { id: 40, name: "Manoplas de horno", cat: "Horno y horneado", locId: "m1-med", freq: "", notes: "" },
  { id: 67, name: "Bandeja de vidrio", cat: "Horno y horneado", locId: "isla-izq-aba", freq: "ocasional", notes: "" },
  { id: 41, name: "Trapos de cocina", cat: "Textil de cocina", locId: "m1-med", freq: "", notes: "" },
  { id: 42, name: "Paños de secado", cat: "Textil de cocina", locId: "m1-med", freq: "", notes: "" },
  { id: 43, name: "Delantales", cat: "Textil de cocina", locId: "m1-med", freq: "", notes: "" },
  { id: 44, name: "Tuppers y fiambreras", cat: "Almacenaje y fiambreras", locId: "m1-aba", freq: "", notes: "" },
  { id: 45, name: "Film transparente", cat: "Almacenaje y fiambreras", locId: null, freq: "", notes: "" },
  { id: 46, name: "Papel aluminio", cat: "Almacenaje y fiambreras", locId: null, freq: "", notes: "" },
  { id: 47, name: "Bolsas de congelación", cat: "Almacenaje y fiambreras", locId: null, freq: "", notes: "" },
  { id: 48, name: "Bolsas de basura", cat: "Almacenaje y fiambreras", locId: null, freq: "", notes: "" },
  { id: 73, name: "Botellitas", cat: "Almacenaje y fiambreras", locId: "esq-mes", freq: "ocasional", notes: "" },
  { id: 74, name: "Termos", cat: "Almacenaje y fiambreras", locId: "esq-mes", freq: "ocasional", notes: "" },
  { id: 49, name: "Cubo basura orgánica", cat: "Residuos y limpieza", locId: "freg", freq: "", notes: "En puerta abatible" },
  { id: 50, name: "Basura resto", cat: "Residuos y limpieza", locId: "esc", freq: "semanal", notes: "" },
  { id: 51, name: "Bolsas reciclaje plástico", cat: "Residuos y limpieza", locId: "esc", freq: "", notes: "" },
  { id: 52, name: "Bolsas reciclaje cartón", cat: "Residuos y limpieza", locId: "esc", freq: "", notes: "" },
  { id: 54, name: "Escoba", cat: "Residuos y limpieza", locId: "esc", freq: "", notes: "" },
  { id: 55, name: "Fregona", cat: "Residuos y limpieza", locId: "esc", freq: "", notes: "" },
  { id: 56, name: "Aspirador", cat: "Residuos y limpieza", locId: "esc", freq: "", notes: "" },
  { id: 57, name: "Detergente lavavajillas", cat: "Residuos y limpieza", locId: null, freq: "", notes: "" },
  { id: 58, name: "Pastillas lavavajillas", cat: "Residuos y limpieza", locId: null, freq: "", notes: "" },
  { id: 59, name: "Bayetas y estropajos", cat: "Residuos y limpieza", locId: null, freq: "", notes: "" },
  { id: 60, name: "Productos limpieza superficies", cat: "Residuos y limpieza", locId: null, freq: "", notes: "" },
  { id: 68, name: "Titan", cat: "Residuos y limpieza", locId: "esc", freq: "diario", notes: "" },
  { id: 70, name: "Residuos papel/cartón", cat: "Residuos y limpieza", locId: "esc", freq: "diario", notes: "" },
  { id: 71, name: "Residuos Plástico", cat: "Residuos y limpieza", locId: "freg", freq: "diario", notes: "" },
  { id: 61, name: "Conservas", cat: "Despensa — alimentos", locId: "arm", freq: "", notes: "" },
  { id: 62, name: "Pasta, arroz, legumbres", cat: "Despensa — alimentos", locId: "arm", freq: "", notes: "" },
  { id: 63, name: "Aceite, vinagre, salsas", cat: "Despensa — alimentos", locId: "arm", freq: "", notes: "" },
  { id: 64, name: "Cereales y snacks niños", cat: "Despensa — alimentos", locId: "arm", freq: "", notes: "" },
  { id: 65, name: "Café, té, infusiones", cat: "Despensa — alimentos", locId: "esq-mes", freq: "diario", notes: "" },
  { id: 66, name: "Azúcar, sal, harina", cat: "Despensa — alimentos", locId: "arm", freq: "", notes: "" },
  { id: 69, name: "Pan", cat: "Despensa — alimentos", locId: null, freq: "semanal", notes: "" },
  { id: 75, name: "Fruta", cat: "Despensa — alimentos", locId: null, freq: "semanal", notes: "" },
  { id: 76, name: "Patatas, boniatos", cat: "Despensa — alimentos", locId: "arm", freq: "semanal", notes: "" },
  { id: 77, name: "Botellas de vino", cat: "Despensa — alimentos", locId: null, freq: "ocasional", notes: "" },
  { id: 72, name: "Azucarero", cat: "Despensa — alimentos", locId: "esq-mes", freq: "ocasional", notes: "" },
  { id: 78, name: "Bolsas para ir a comprar", cat: "Varios", locId: "esc", freq: "semanal", notes: "" },
];
