-- Esquema inicial: locations, categories, items (app de cocina)

create table public.locations (
  id   text primary key,
  name text not null,
  "desc" text default '',
  w    numeric,
  d    numeric,
  h    numeric
);

create table public.categories (
  id   integer generated always as identity primary key,
  name text unique not null
);

create table public.items (
  id     bigint generated by default as identity primary key,
  name   text not null,
  cat    text not null,
  loc_id text references public.locations(id) on delete set null,
  freq   text default '',
  notes  text default ''
);

create index items_loc_id_idx on public.items (loc_id);
create index items_cat_idx    on public.items (cat);

-- RLS activado con políticas abiertas (app personal sin autenticación)
alter table public.locations  enable row level security;
alter table public.categories enable row level security;
alter table public.items      enable row level security;

create policy "open_locations"  on public.locations  for all to anon, authenticated using (true) with check (true);
create policy "open_categories" on public.categories for all to anon, authenticated using (true) with check (true);
create policy "open_items"      on public.items      for all to anon, authenticated using (true) with check (true);
