-- Datos semilla: 22 ubicaciones, 11 categorías, 76 items.
-- (también disponibles en lib/seed.ts para la función "Restaurar datos")

insert into public.locations (id, name, "desc", w, d, h) values
('arm','Armario despensa','Columna 60cm — alimentos',0.6,0.6,2.5),
('nev','Nevera','Módulo 70cm',0.7,0.6,2),
('nev-alto','Mueble alto nevera','Mueble alto 70cm',0.7,0.35,0.6),
('m1-arr','M1 — Cajón arriba','Utensilios de cocina',0.9,0.6,0.3),
('m1-med','M1 — Cajón medio','Trapos, manoplas, textil',0.9,0.6,0.35),
('m1-aba','M1 — Cajón abajo','Tuppers y fiambreras',0.9,0.6,0.4),
('freg','Bajo fregadero','Puerta abatible — residuos',0.7,0.6,0.9),
('lvj','Encimera lavavajillas','Superficie libre de apoyo',0.6,0.6,0.05),
('hor-hue','Horno — Hueco superior','Pendiente',0.6,0.6,0.7),
('hor-aba1','Horno — Cajón abajo 1','Pendiente',0.6,0.6,0.3),
('hor-aba2','Horno — Cajón abajo 2','Bandejas, rejillas, papel horno',0.6,0.6,0.3),
('esc','Escobero','70cm — limpieza y reciclaje',0.7,0.6,2.5),
('isla-izq-arr','Isla izq — Cajón arriba','Especias y condimentos',0.9,0.6,0.3),
('isla-izq-med','Isla izq — Cajón medio','Sartenes y tapas',0.9,0.6,0.3),
('isla-izq-aba','Isla izq — Cajón abajo','Ollas y cazuelas',0.9,0.6,0.4),
('isla-der-arr','Isla der — Cajón arriba','Cubiertos',0.9,0.6,0.3),
('isla-der-med','Isla der — Cajón medio','Platos, tazas y bols',0.9,0.6,0.3),
('isla-der-aba','Isla der — Cajón abajo','Vasos y copas',0.9,0.6,0.4),
('esq-arr','Esquinero — Cajones arriba','Pendiente',1,0.4,0.4),
('esq-mes','Esquinero — Mesada','Electrodomésticos pequeños',1,0.4,0.05),
('esq-aba','Esquinero — Cajones abajo','Pendiente',1,0.4,0.4),
('estante','Estante corrido 150cm','A 150cm altura — zona fregadero',2.2,0.35,0.05);

insert into public.categories (name) values
('Electrodomésticos grandes'),
('Electrodomésticos pequeños'),
('Vajilla y mesa'),
('Utensilios de cocina'),
('Sartenes, ollas y cazuelas'),
('Horno y horneado'),
('Textil de cocina'),
('Almacenaje y fiambreras'),
('Residuos y limpieza'),
('Despensa — alimentos'),
('Varios');

insert into public.items (id, name, cat, loc_id, freq, notes) values
(1,'Nevera','Electrodomésticos grandes','nev','',''),
(2,'Lavavajillas','Electrodomésticos grandes','lvj','',''),
(3,'Horno','Electrodomésticos grandes','hor-hue','',''),
(4,'Placa de inducción (con extracción)','Electrodomésticos grandes','isla-izq-arr','','Centrada en 2,1m isla'),
(5,'Microondas','Electrodomésticos pequeños','esq-mes','',''),
(6,'Cafetera','Electrodomésticos pequeños','esq-mes','',''),
(7,'Tostadora','Electrodomésticos pequeños','esq-mes','',''),
(8,'Calentador de agua','Electrodomésticos pequeños','esq-mes','',''),
(9,'Robot de cocina / batidora de vaso','Electrodomésticos pequeños','m1-med','','Uso ocasional'),
(11,'Platos','Vajilla y mesa','isla-der-med','',''),
(12,'Vasos','Vajilla y mesa','isla-der-aba','',''),
(13,'Bols','Vajilla y mesa','isla-der-med','',''),
(14,'Tazas','Vajilla y mesa','isla-der-med','',''),
(15,'Cubiertos (cuchillos, tenedores...)','Vajilla y mesa','isla-der-arr','',''),
(16,'Vajilla especial / de fiesta','Vajilla y mesa','nev-alto','',''),
(17,'Fuentes grandes','Vajilla y mesa','nev-alto','',''),
(18,'Copas','Vajilla y mesa','isla-der-aba','',''),
(19,'Servilletas y mantelería','Vajilla y mesa',null,'',''),
(20,'Espátulas','Utensilios de cocina','isla-der-arr','diario',''),
(21,'Pelador','Utensilios de cocina','m1-arr','',''),
(22,'Tijeras de cocina','Utensilios de cocina','m1-arr','',''),
(23,'Pinzas','Utensilios de cocina','m1-arr','',''),
(24,'Cucharones y espumaderas','Utensilios de cocina','isla-der-arr','diario',''),
(25,'Abrebotellas / sacacorchos','Utensilios de cocina',null,'',''),
(26,'Rallador','Utensilios de cocina','m1-arr','',''),
(27,'Colador / escurridor','Utensilios de cocina',null,'',''),
(28,'Batidor de mano','Utensilios de cocina','m1-med','',''),
(29,'Cuchillos (bloque o soporte)','Utensilios de cocina',null,'',''),
(30,'Sartenes','Sartenes, ollas y cazuelas','isla-izq-med','',''),
(31,'Cazuelas','Sartenes, ollas y cazuelas','isla-izq-aba','',''),
(32,'Ollas','Sartenes, ollas y cazuelas','isla-izq-aba','',''),
(33,'Especias y condimentos','Sartenes, ollas y cazuelas','isla-izq-arr','',''),
(34,'Tapas de ollas y sartenes','Sartenes, ollas y cazuelas','isla-izq-med','',''),
(35,'Bandejas del horno','Horno y horneado','hor-aba2','',''),
(36,'Rejillas del horno','Horno y horneado','hor-aba2','',''),
(37,'Papel de horno','Horno y horneado','hor-aba2','',''),
(38,'Tablas de cortar','Horno y horneado','hor-aba2','',''),
(39,'Moldes (cake, muffins, pizza...)','Horno y horneado',null,'',''),
(40,'Manoplas de horno','Horno y horneado','m1-med','',''),
(67,'Bandeja de vidrio','Horno y horneado','isla-izq-aba','ocasional',''),
(41,'Trapos de cocina','Textil de cocina','m1-med','',''),
(42,'Paños de secado','Textil de cocina','m1-med','',''),
(43,'Delantales','Textil de cocina','m1-med','',''),
(44,'Tuppers y fiambreras','Almacenaje y fiambreras','m1-aba','',''),
(45,'Film transparente','Almacenaje y fiambreras',null,'',''),
(46,'Papel aluminio','Almacenaje y fiambreras',null,'',''),
(47,'Bolsas de congelación','Almacenaje y fiambreras',null,'',''),
(48,'Bolsas de basura','Almacenaje y fiambreras',null,'',''),
(73,'Botellitas','Almacenaje y fiambreras','esq-mes','ocasional',''),
(74,'Termos','Almacenaje y fiambreras','esq-mes','ocasional',''),
(49,'Cubo basura orgánica','Residuos y limpieza','freg','','En puerta abatible'),
(50,'Basura resto','Residuos y limpieza','esc','semanal',''),
(51,'Bolsas reciclaje plástico','Residuos y limpieza','esc','',''),
(52,'Bolsas reciclaje cartón','Residuos y limpieza','esc','',''),
(54,'Escoba','Residuos y limpieza','esc','',''),
(55,'Fregona','Residuos y limpieza','esc','',''),
(56,'Aspirador','Residuos y limpieza','esc','',''),
(57,'Detergente lavavajillas','Residuos y limpieza',null,'',''),
(58,'Pastillas lavavajillas','Residuos y limpieza',null,'',''),
(59,'Bayetas y estropajos','Residuos y limpieza',null,'',''),
(60,'Productos limpieza superficies','Residuos y limpieza',null,'',''),
(68,'Titan','Residuos y limpieza','esc','diario',''),
(70,'Residuos papel/cartón','Residuos y limpieza','esc','diario',''),
(71,'Residuos Plástico','Residuos y limpieza','freg','diario',''),
(61,'Conservas','Despensa — alimentos','arm','',''),
(62,'Pasta, arroz, legumbres','Despensa — alimentos','arm','',''),
(63,'Aceite, vinagre, salsas','Despensa — alimentos','arm','',''),
(64,'Cereales y snacks niños','Despensa — alimentos','arm','',''),
(65,'Café, té, infusiones','Despensa — alimentos','esq-mes','diario',''),
(66,'Azúcar, sal, harina','Despensa — alimentos','arm','',''),
(69,'Pan','Despensa — alimentos',null,'semanal',''),
(75,'Fruta','Despensa — alimentos',null,'semanal',''),
(76,'Patatas, boniatos','Despensa — alimentos','arm','semanal',''),
(77,'Botellas de vino','Despensa — alimentos',null,'ocasional',''),
(72,'Azucarero','Despensa — alimentos','esq-mes','ocasional',''),
(78,'Bolsas para ir a comprar','Varios','esc','semanal','');

select setval(pg_get_serial_sequence('public.items','id'), (select max(id) from public.items));
